password_policy.settings:
  type: config_object
  label: 'Password Policy settings'
  mapping:
    min_character_length:
      type: boolean
      label: 'Minimal character length of users password'
    digit_characters:
      type: boolean
      label: 'Minimal digital characters number in users password'
    lowercased_characters:
      type: boolean
      label: 'Minimal lowercased characters number in users password'
    uppercased_characters:
      type: boolean
      label: 'Minimal uppercased characters number in users password'
    special_characters:
      type: boolean
      label: 'Minimal special characters number in users password'
